In [2]:
#import the dataset
import pandas as pd

#Load the dataset
data= pd.read_csv("raw_dataset.csv")
data.head()

,acc_code,incident_datetime,report_datetime,province_en,agency,vehicle_type,presumed_cause,accident_type,number_of_vehicles_involved,number_of_fatalities,number_of_injuries,weather_condition,latitude,longitude,road_description,slope_description
0,571905,01/01/2019 00:00,01/02/2019 06:11,Loburi,department of rural roads,motorcycle,driving under the influence of alcohol,other,1,0,2,clear,14.959105,100.873463,straight road,no slope
1,3790870,01/01/2019 00:03,02/20/2020 13:48,Ubon Ratchathani,department of highways,private/passenger car,speeding,rollover/fallen on straight road,1,0,2,clear,15.210738,104.862689,straight road,no slope
2,599075,01/01/2019 00:05,01/01/2019 10:35,Prachuap Khiri Khan,department of highways,motorcycle,speeding,head-on collision (not overtaking),2,1,0,clear,12.374259,99.907949,wide curve,slope area
3,571924,01/01/2019 00:20,01/02/2019 05:12,Chiang Mai,department of rural roads,motorcycle,driving under the influence of alcohol,other,1,0,1,clear,18.601721,98.804204,straight road,no slope
4,599523,01/01/2019 00:25,01/04/2019 09:42,Nakhon Sawan,department of highways,private/passenger car,cutting in closely by people/vehicles/animals,rollover/fallen on straight road,1,0,0,clear,15.866389,100.590010,straight road,no slope

In [3]:
#Check for missing values
print(data.isnull().sum())

acc_code                         0
incident_datetime                0
report_datetime                  0
province_en                      0
agency                           0
vehicle_type                     0
presumed_cause                   0
accident_type                    0
number_of_vehicles_involved      0
number_of_fatalities             0
number_of_injuries               0
weather_condition                0
latitude                       359
longitude                      359
road_description                 0
slope_description                0
dtype: int64

In [4]:
#Remove missing values
data_clean=data.dropna()
print(data_clean.isnull().sum())

acc_code                       0
incident_datetime              0
report_datetime                0
province_en                    0
agency                         0
vehicle_type                   0
presumed_cause                 0
accident_type                  0
number_of_vehicles_involved    0
number_of_fatalities           0
number_of_injuries             0
weather_condition              0
latitude                       0
longitude                      0
road_description               0
slope_description              0
dtype: int64

In [5]:
#Check for duplicates
print(data.duplicated().sum())
data_clean= data. drop_duplicates()
data.head()

0

,acc_code,incident_datetime,report_datetime,province_en,agency,vehicle_type,presumed_cause,accident_type,number_of_vehicles_involved,number_of_fatalities,number_of_injuries,weather_condition,latitude,longitude,road_description,slope_description
0,571905,01/01/2019 00:00,01/02/2019 06:11,Loburi,department of rural roads,motorcycle,driving under the influence of alcohol,other,1,0,2,clear,14.959105,100.873463,straight road,no slope
1,3790870,01/01/2019 00:03,02/20/2020 13:48,Ubon Ratchathani,department of highways,private/passenger car,speeding,rollover/fallen on straight road,1,0,2,clear,15.210738,104.862689,straight road,no slope
2,599075,01/01/2019 00:05,01/01/2019 10:35,Prachuap Khiri Khan,department of highways,motorcycle,speeding,head-on collision (not overtaking),2,1,0,clear,12.374259,99.907949,wide curve,slope area
3,571924,01/01/2019 00:20,01/02/2019 05:12,Chiang Mai,department of rural roads,motorcycle,driving under the influence of alcohol,other,1,0,1,clear,18.601721,98.804204,straight road,no slope
4,599523,01/01/2019 00:25,01/04/2019 09:42,Nakhon Sawan,department of highways,private/passenger car,cutting in closely by people/vehicles/animals,rollover/fallen on straight road,1,0,0,clear,15.866389,100.590010,straight road,no slope

In [6]:
#Check datatypes
print(data_clean.dtypes)

acc_code                         int64
incident_datetime               object
report_datetime                 object
province_en                     object
agency                          object
vehicle_type                    object
presumed_cause                  object
accident_type                   object
number_of_vehicles_involved      int64
number_of_fatalities             int64
number_of_injuries               int64
weather_condition               object
latitude                       float64
longitude                      float64
road_description                object
slope_description               object
dtype: object

In [7]:
data_clean['incident_datetime']= pd.to_datetime(data['incident_datetime'])
data_clean['report_datetime']= pd.to_datetime(data['report_datetime'])

print(data_clean.dtypes)

acc_code                                int64
incident_datetime              datetime64[ns]
report_datetime                datetime64[ns]
province_en                            object
agency                                 object
vehicle_type                           object
presumed_cause                         object
accident_type                          object
number_of_vehicles_involved             int64
number_of_fatalities                    int64
number_of_injuries                      int64
weather_condition                      object
latitude                              float64
longitude                             float64
road_description                       object
slope_description                      object
dtype: object

In [8]:
#Renaming columns
data_clean.rename(columns={'incident_datetime':'Incident DateTime','report_datetime':'Report DateTime','province_en':'Province'}, inplace=True)
data_clean.head()

,acc_code,Incident DateTime,Report DateTime,Province,agency,vehicle_type,presumed_cause,accident_type,number_of_vehicles_involved,number_of_fatalities,number_of_injuries,weather_condition,latitude,longitude,road_description,slope_description
0,571905,2019-01-01 00:00:00,2019-01-02 06:11:00,Loburi,department of rural roads,motorcycle,driving under the influence of alcohol,other,1,0,2,clear,14.959105,100.873463,straight road,no slope
1,3790870,2019-01-01 00:03:00,2020-02-20 13:48:00,Ubon Ratchathani,department of highways,private/passenger car,speeding,rollover/fallen on straight road,1,0,2,clear,15.210738,104.862689,straight road,no slope
2,599075,2019-01-01 00:05:00,2019-01-01 10:35:00,Prachuap Khiri Khan,department of highways,motorcycle,speeding,head-on collision (not overtaking),2,1,0,clear,12.374259,99.907949,wide curve,slope area
3,571924,2019-01-01 00:20:00,2019-01-02 05:12:00,Chiang Mai,department of rural roads,motorcycle,driving under the influence of alcohol,other,1,0,1,clear,18.601721,98.804204,straight road,no slope
4,599523,2019-01-01 00:25:00,2019-01-04 09:42:00,Nakhon Sawan,department of highways,private/passenger car,cutting in closely by people/vehicles/animals,rollover/fallen on straight road,1,0,0,clear,15.866389,100.590010,straight road,no slope

In [9]:
#save clean dataset
data_clean.to_csv('clean_dataset.csv',index=False)
df=pd.read_csv('clean_dataset.csv',parse_dates=['Incident DateTime', 'Report DateTime'])
df.head()
print(df.dtypes)

acc_code                                int64
Incident DateTime              datetime64[ns]
Report DateTime                datetime64[ns]
Province                               object
agency                                 object
vehicle_type                           object
presumed_cause                         object
accident_type                          object
number_of_vehicles_involved             int64
number_of_fatalities                    int64
number_of_injuries                      int64
weather_condition                      object
latitude                              float64
longitude                             float64
road_description                       object
slope_description                      object
dtype: object

In [10]:
#Generating statistics
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81735 entries, 0 to 81734
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   acc_code                     81735 non-null  int64
 1   Incident DateTime            81735 non-null  datetime64[ns]
 2   Report DateTime              81735 non-null  datetime64[ns]
 3   Province                     81735 non-null  object
 4   agency                       81735 non-null  object
 5   vehicle_type                 81735 non-null  object
 6   presumed_cause               81735 non-null  object
 7   accident_type                81735 non-null  object
 8   number_of_vehicles_involved  81735 non-null  int64
 9   number_of_fatalities         81735 non-null  int64
 10  number_of_injuries           81735 non-null  int64
 11  weather_condition            81735 non-null  object
 12  latitude                     81376 non-null  float64
 13  longitude                    81376 non-null  float64
 14  road_description             81735 non-null  object
 15  slope_description            81735 non-null  object
dtypes: datetime64[ns](2), float64(2), int64(4), object(8)
memory usage: 10.0+ MB

In [11]:
data_clean.describe(include='all')

,acc_code,Incident DateTime,Report DateTime,Province,agency,vehicle_type,presumed_cause,accident_type,number_of_vehicles_involved,number_of_fatalities,number_of_injuries,weather_condition,latitude,longitude,road_description,slope_description
count,8.173500e+04,81735,81735,81735,81735,81735,81735,81735,81735.000000,81735.000000,81735.000000,81735,81376.000000,81376.000000,81735,81735
unique,NaN,NaN,NaN,78,3,15,54,11,NaN,NaN,NaN,7,NaN,NaN,19,3
top,NaN,NaN,NaN,Bangkok,department of highways,4-wheel pickup truck,speeding,rollover/fallen on straight road,NaN,NaN,NaN,clear,NaN,NaN,straight road,no slope
freq,NaN,NaN,NaN,6439,75304,28445,60373,33046,NaN,NaN,NaN,69943,NaN,NaN,58183,65797
mean,4.235766e+06,2021-01-10 02:05:53.076160768,2021-03-28 04:33:21.037988608,NaN,NaN,NaN,NaN,NaN,1.534704,0.145568,0.811855,NaN,14.377542,100.808802,NaN,NaN
min,5.718340e+05,2019-01-01 00:00:00,2019-01-01 03:05:00,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,-0.001108,18.017161,NaN,NaN
25%,3.789460e+06,2020-01-17 23:30:00,2020-03-20 08:45:30,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,NaN,13.510107,99.885506,NaN,NaN
50%,3.824084e+06,2021-01-03 14:30:00,2021-03-31 10:06:00,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,NaN,14.468878,100.555529,NaN,NaN
75%,5.831088e+06,2022-01-03 10:55:00,2022-03-01 11:08:30,NaN,NaN,NaN,NaN,NaN,2.000000,0.000000,1.000000,NaN,16.567408,101.292237,NaN,NaN
max,7.571316e+06,2022-12-31 23:55:00,2023-01-26 13:20:00,NaN,NaN,NaN,NaN,NaN,27.000000,13.000000,51.000000,NaN,41.549515,105.517239,NaN,NaN
std,2.128207e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.807395,0.433816,1.461861,NaN,3.065689,1.484859,NaN,NaN

In [12]:
#summary of the dataset
import pandas as pd
data=pd.read_csv('clean_dataset.csv')
data[['number_of_vehicles_involved','number_of_fatalities','number_of_injuries']].describe()

       number_of_vehicles_involved  number_of_fatalities  number_of_injuries
count                 81735.000000          81735.000000        81735.000000
mean                      1.534704              0.145568            0.811855
std                       0.807395              0.433816            1.461861
min                       0.000000              0.000000            0.000000
25%                       1.000000              0.000000            0.000000
50%                       1.000000              0.000000            0.000000
75%                       2.000000              0.000000            1.000000
max                      27.000000             13.000000           51.000000

In [13]:
#Yearly accident count(2019-2022)
data=pd.read_csv('clean_dataset.csv')
data['Incident DateTime']= pd.to_datetime(data['Incident DateTime'])
data_clean['year']= data_clean['Incident DateTime'].dt.year

data_clean['year'].value_counts().sort_index()

year
2019    19194
2020    21052
2021    20457
2022    21032
Name: count, dtype: int64

In [14]:
#Data Grouping by Province
Province_accidents= df.groupby('Province').size().sort_values(ascending=False)
print(Province_accidents)

Province
Bangkok              6439
Chon Buri            4120
Chiang Mai           3407
Nakhon Ratchasima    3330
Suphan Buri          3056
                     ...
Nong Bua Lam Phu      288
Phichit               226
Amnat Charoen         196
Ranong                140
unknown                34
Length: 78, dtype: int64

In [15]:
#Number of fatalities by province
Casualties=df.groupby('Province')['number_of_fatalities'].sum().sort_values(ascending=False)
print(Casualties)

Province
Suphan Buri          456
Nakhon Ratchasima    455
Surat Thani          334
Chiang Mai           332
Chanthaburi          326
                    ...
Phuket                37
Mae Hong Son          34
Yala                  28
Ranong                26
unknown                8
Name: number_of_fatalities, Length: 78, dtype: int64

In [16]:
#Number of accidents by accident type
accident_type=df.groupby('accident_type').size().sort_values(ascending=False)
print(accident_type)

accident_type
rollover/fallen on straight road                33046
rear-end collision                              24901
rollover/fallen on curved road                  10443
other                                            4188
head-on collision (not overtaking)               3944
collision with obstruction (on road surface)     2742
collision at intersection corner                 1067
pedestrian collision                              945
side collision                                    336
collision during overtaking                        83
turning/retreating collision                       40
dtype: int64

In [17]:
#Number of accidents by vehicle type
Vehicle_type=df.groupby('vehicle_type').size().sort_values(ascending=False)
print(Vehicle_type)

vehicle_type
4-wheel pickup truck            28445
private/passenger car           20814
motorcycle                      14874
large truck with trailer         6257
other                            3513
6-wheel truck                    3019
7-10-wheel truck                 2364
van                               842
large passenger vehicle           421
passenger pickup truck            325
motorized tricycle                294
bicycle                           257
pedestrian                        219
tractor/agricultural vehicle       63
three-wheeled vehicle              28
dtype: int64

In [18]:
#Average number of fatalities by vehicle type
vehicle_mean=df.groupby('vehicle_type')['number_of_fatalities'].mean().sort_values(ascending=False)
print(vehicle_mean)

vehicle_type
pedestrian                      0.726027
bicycle                         0.439689
three-wheeled vehicle           0.428571
motorized tricycle              0.425170
motorcycle                      0.350881
tractor/agricultural vehicle    0.269841
passenger pickup truck          0.252308
large passenger vehicle         0.218527
van                             0.173397
6-wheel truck                   0.114276
large truck with trailer        0.098929
7-10-wheel truck                0.098562
private/passenger car           0.094167
4-wheel pickup truck            0.092213
other                           0.043553
Name: number_of_fatalities, dtype: float64

In [19]:
#Number of accidents by weather condition
weather_accidents=df.groupby('weather_condition').size().sort_values(ascending=False)
print(weather_accidents)

weather_condition
clear               69943
rainy               10670
foggy                 544
dark                  368
other                 162
natural disaster       47
land slide              1
dtype: int64

In [20]:
slope_accidents=df.groupby('slope_description').size().sort_values(ascending=False)
print(slope_accidents)

slope_description
no slope      65797
other         11575
slope area     4363
dtype: int64

In [21]:
road_description= df.groupby('road_description').size().sort_values(ascending=False)
print(road_description)

road_description
straight road                           58183
wide curve                              12552
other                                    7614
connecting to public/commercial area     1001
sharp curve                               616
connecting to private area                463
t-intersection                            414
four-way intersection                     348
grade-separated intersection/ramps        184
y-intersection                            184
connecting to school area                 121
merge lane                                 19
roundabout                                 11
u-turn area                                10
lane-changing area                          7
bridge (across river/canal)                 5
pedestrian path                             1
motorcycle lane                             1
zebra crossing/pedestrian crossing          1
dtype: int64

In [22]:
#Number of accidents by time of day
accidents_time=df.groupby(df['Incident DateTime'].dt.hour).size().sort_values(ascending=False)
print(accidents_time)

Incident DateTime
15    4555
16    4550
14    4402
19    4131
13    4122
17    4096
10    4091
11    3989
9     3851
18    3770
8     3684
12    3675
20    3559
7     3483
21    3217
23    2873
22    2792
1     2635
0     2590
6     2528
5     2436
2     2354
4     2227
3     2125
dtype: int64